# Generated by Django 3.2.4 on 2021-06-19 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('percentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='polls',
            name='options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Options', to='api.optionspoll'),
        ),
    ]
