# Generated by Django 3.2.4 on 2021-06-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210619_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='options',
        ),
        migrations.AddField(
            model_name='polls',
            name='options',
            field=models.ManyToManyField(related_name='Options', to='api.OptionsPoll'),
        ),
    ]
