# Generated by Django 3.2.4 on 2021-06-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210619_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='options',
        ),
        migrations.AddField(
            model_name='optionspoll',
            name='fk_poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.polls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionspoll',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polls',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
